### PR TITLE
Eirene

### PR DESCRIPTION
**Pull request by mira-miracoli**
PR for triggering Jenkins, original was
- #188

### CODE REVIEW

**Comment by hechth** [comment]
@bgruening can this be merged?

**Comment by mira-miracoli** [comment]
There was a merge conflict because we updated another subdomain in the meantime. the CI is running again. sorry

**Comment by mira-miracoli** [comment]
I think this is what we want :)

**Comment by hechth** [comment]
Thanks a lot :)

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
