### PR TITLE
Update uploads instance to Rocky Linux 9

### PR DESCRIPTION
**Pull request by kysrpex**
Update the uploads machine to Rocky Linux 9.

### CODE REVIEW

**Comment by bgruening** [comment]
Can one of the admins verify this patch?

**Comment by sanjaysrikakulam** [comment]
NOTE: `generic-internal-v60-j333-fb0029b7a329-dev` Image does not exist in the main project. It should be uploaded.

**Comment by kysrpex** [comment]
> NOTE: `generic-internal-v60-j333-fb0029b7a329-dev` Image does not exist in the main project. It should be uploaded.

Strange, [Jenkins logs](https://build.galaxyproject.eu/job/usegalaxy-eu/job/vgcn-bwcloud-image/128/console) do not show anything strange concerning the upload.

**Comment by sanjaysrikakulam** [comment]
> > NOTE: `generic-internal-v60-j333-fb0029b7a329-dev` Image does not exist in the main project. It should be uploaded.
> 
> Strange, [Jenkins logs](https://build.galaxyproject.eu/job/usegalaxy-eu/job/vgcn-bwcloud-image/128/console) do not show anything out of the ordinary concerning the upload.

I meant that the image is not yet in the BWCloud tenant.

**Comment by sanjaysrikakulam** [comment]
Ok, the image is there, sorry for the confusion.

**Comment by kysrpex** [comment]
> > > NOTE: `generic-internal-v60-j333-fb0029b7a329-dev` Image does not exist in the main project. It should be uploaded.
> > 
> > 
> > Strange, [Jenkins logs](https://build.galaxyproject.eu/job/usegalaxy-eu/job/vgcn-bwcloud-image/128/console) do not show anything out of the ordinary concerning the upload.
> 
> I meant that the image is not yet in the BWCloud tenant.

External images use a different naming scheme, this image can be found on https://usegalaxy.eu/static/vgcn/ under the name [vggp-v60-j333-fb0029b7a329-dev.raw](https://usegalaxy.eu/static/vgcn/vggp-v60-j333-fb0029b7a329-dev.raw).

**Review by sanjaysrikakulam — APPROVED** [review]

**Comment by sanjaysrikakulam** [comment]
I think you will have to convert this PR into an internal PR (add your branch to the upstream and then create the PR) otherwise we do not get the PR build job running.

**Pull request closed without merging**
