### PR TITLE
Beacon importer image

### PR DESCRIPTION
**Pull request by mira-miracoli**
Using the
`vgcn~rockylinux-9.2-x86_64~+generic+internal~20240102~70050~dev~6f78a5f~mira_local_build`
I built with the build.py script. I tested the image briefly by launching and ssh into the vm.

### CODE REVIEW

**Comment by mira-miracoli** [comment]
Did someone manually delete the subdomains and forgot to change it in terraform or was it my mistake 👀

**Comment by bgruening** [comment]
I don't know. @sanjaysrikakulam did some subdomain magic afaik. Maybe he knows if this is normal?

**Comment by sanjaysrikakulam** [comment]
My earlier PR related to the subdomains failed (Jenkins build failed) because of a missing attribute; hence, it shows that it needs to create all the subdomains. The subdomains are intact and working. I have created a follow-up [PR] (https://github.com/usegalaxy-eu/infrastructure/pull/184) addressing that. Once that's deployed, we will not see this bot output.

**Comment by mira-miracoli** [comment]
new tf plan needed

**Comment by mira-miracoli** [comment]
second try

**Review by sanjaysrikakulam — APPROVED** [review]

**Pull request merged**
