### PR TITLE
Beacon

### PR DESCRIPTION
**Pull request by mira-miracoli**
Changed beacond images to bw cloud Rocky 9 image

### CODE REVIEW

**Comment by bgruening** [comment]
Can one of the admins verify this patch?

**Review by sanjaysrikakulam — APPROVED** [review]

**Comment by sanjaysrikakulam** [comment]
I hope that image (c6906a58-1e05-4be0-8f20-41f24c8320b5) is available in the main tenant. I do not have access to check it.

**Comment by mira-miracoli** [comment]
It's there, I will merge it

**Comment by sanjaysrikakulam** [comment]
Cool, please go ahead.

**Pull request merged**
