### PR TITLE
Remove fr vms ON WEDNESDAY

### PR DESCRIPTION
**Pull request by abretaud**
Merge only on Wednesday if possible :)
Thanks again for hosting them!

### CODE REVIEW

**Comment by bgruening** [comment]
Can one of the admins verify this patch?

**Review by hexylena — APPROVED** [review]
looks fine! will hit merge on wednesday

**Comment by hexylena** [comment]
@abretaud good to merge?

ok to test.

**Comment by hexylena** [comment]
Huh, that plan isn't right at all.

**Comment by gmauro** [comment]
That's an issue I'm trying to fix right now. Let you know

**Comment by gmauro** [comment]
OK, the volume has been brutally convinced to leave this world.

**Comment by hexylena** [comment]
test this please

**Comment by hexylena** [comment]
Oh, anthony is in holiday I think. I'll just merge this at end-of-eu-workday then.

**Pull request merged**
