### PR TITLE
Remove Ryan's dedicated VM

### PR DESCRIPTION
**Pull request by kysrpex**
We agreed that this VM can be cleaned up, so let's remove it.

### CODE REVIEW

**Comment by bgruening** [comment]
Can one of the admins verify this patch?

**Review by mira-miracoli — APPROVED** [review]

**Comment by mira-miracoli** [comment]
I wonder why @usegalaxy-eu-bot did not comment with the `terraform plan`

**Comment by kysrpex** [comment]
> I wonder why @usegalaxy-eu-bot did not comment with the `terraform plan`

I made a draft first that's why, I think. I did not want to make noise before the bot ran. I achieved the opposite effect.

I'll take care of this and request review again.

**Comment by mira-miracoli** [comment]
I mean it should be simple in this case, but good that you noted this with the draft, I wouldn't have thought about that either

**Comment by sanjaysrikakulam** [comment]
> > I wonder why @usegalaxy-eu-bot did not comment with the `terraform plan`
> 
> I made a draft first that's why, I think. I did not want to make noise before the bot ran. I achieved the opposite effect.
> 
> I'll take care of this or do what the bot does myself as a sanity check and post it here.

The bot did not run because the PR branch is not internal. For the bot to work, the PRs must come from an internal branch of this repo.

**Comment by bgruening** [comment]
That makes a lot of sense!

**Pull request merged**
