### PR TITLE
add new volume

### PR DESCRIPTION
**Pull request by gmauro**
No more space in test. I am moving /opt in a separated volume

### CODE REVIEW

**Comment by erasche** [comment]
What is taking up that space? It has not been needed until now, maybe there's an easy parameter change that I missed? we have so much space on /data/*, volumes mostly are not needed in `bioinf` net, we really only use them outside of bioinf.

**Comment by gmauro** [comment]
The vm has only 12GB:
/opt ~ 6GB
/var ~ 2GB
/usr/*(not local) ~3GB
and with the others dirs, the disk is full.

**Comment by erasche** [comment]
That doesn't really answer my question: why is there 6GB in /opt, there **should** only be the server code + config + shed tool conf. Is it the conda dependency dir? This could be moved to NFS?

**Comment by gmauro** [comment]
fixed by https://github.com/usegalaxy-eu/infrastructure-playbook/pull/77

**Pull request closed without merging**
