### PR TITLE
gxit DNS entries

### PR DESCRIPTION
**Pull request by hexylena**
- add encrypt/decrypt routines in the makefile (needed for tainting)
- taint the first three gat VMs to force a rebuild
- enable GXIT DNS entries for EU, US, OZ machines now that they're assigned.

### CODE REVIEW

**Comment by hexylena** [comment]
guess I overwhelmed openstack :|

**Comment by gmauro** [comment]
I have seen also a "glitch" on OpenStack

**Comment by hexylena** [comment]
Should I push another commit to retrigger the test? What would you like to do here?

**Comment by gmauro** [comment]
yes, please

**Comment by hexylena** [comment]
I think that plan looks good?

**Pull request merged**
